# Introduction

In [1]:
import requests
import zipfile
import io
import os
import glob

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [2]:
folder_name = 'EPM'
if not os.path.exists(folder_name):
    os.makedirs(folder_name)

# Gathering Data

Download dataset:

In [3]:
url = 'http://archive.ics.uci.edu/ml/machine-learning-databases/00346/EPMDataset%20.zip'
r = requests.get(url)
z = zipfile.ZipFile(io.BytesIO(r.content))
z.extractall(path='/Users/Mysun/Desktop/HU 530/530 - Project')

Input all the sessions data:

In [4]:
# read all the session data and save them into a dictionary
sessions = {}
for x in range(1, 7):
    path = '/Users/Mysun/Desktop/HU 530/530 - Project/EPM Dataset 2/Data/Processes/Session {0}'.format(x)
    session = glob.glob(os.path.join(path, '*'))
    dataframes = (pd.read_csv(f, names=['session', 'student_Id', 'exercise', 'activity',
                                        'start_time', 'end_time', 'idle_time', 'mouse_wheel', 
                                        'mouse_wheel_click', 'mouse_click_left', 'mouse_click_right', 
                                        'mouse_movement', 'keystroke']) for f in session)
    sessions['session{0}'.format(x)] = pd.concat(dataframes, ignore_index=True, sort=False)

In [5]:
sessions['session1'].head()

,session,student_Id,exercise,activity,start_time,end_time,idle_time,mouse_wheel,mouse_wheel_click,mouse_click_left,mouse_click_right,mouse_movement,keystroke
0,1,59,Es,Other,2.10.2014 11:24:0,2.10.2014 11:24:3,421,0,0,2,0,106,0
1,1,59,Es,Deeds,2.10.2014 11:24:5,2.10.2014 11:25:42,4573639,0,0,2,0,107,0
2,1,59,Es,Blank,2.10.2014 11:25:43,2.10.2014 11:25:44,0,0,0,2,0,123,0
3,1,59,Es_1_1,Study_Es_1_1,2.10.2014 11:25:45,2.10.2014 11:26:46,1652751,0,0,2,0,107,0
4,1,59,Es_1_1,Deeds,2.10.2014 11:26:47,2.10.2014 11:26:47,0,0,0,2,0,18,0

In [6]:
sessions['session2'].head()

,session,student_Id,exercise,activity,start_time,end_time,idle_time,mouse_wheel,mouse_wheel_click,mouse_click_left,mouse_click_right,mouse_movement,keystroke
0,2,61,Es,Other,16.10.2014 11:55:13,16.10.2014 11:55:20,1607,0,0,2,0,350,0
1,2,61,Es,Aulaweb,16.10.2014 11:55:21,16.10.2014 11:55:26,94,7,0,8,0,334,0
2,2,61,Es_2_1,TextEditor_Es_2_1,16.10.2014 11:55:27,16.10.2014 11:55:31,217,3,0,8,0,210,6
3,2,61,Es_2_1,Study_Es_2_1,16.10.2014 11:55:32,16.10.2014 11:55:33,16,0,0,0,0,0,9
4,2,61,Es_2_1,Aulaweb,16.10.2014 11:55:34,16.10.2014 11:55:34,0,0,0,0,0,0,2

In [7]:
sessions['session6'].tail()

,session,student_Id,exercise,activity,start_time,end_time,idle_time,mouse_wheel,mouse_wheel_click,mouse_click_left,mouse_click_right,mouse_movement,keystroke
53165,6,25,Es_6_3,Study_Es_6_3,11.12.2014 14:23:23,11.12.2014 14:23:25,15,0,0,2,0,40,0
53166,6,25,Es_6_3,Other,11.12.2014 14:23:26,11.12.2014 14:23:29,157,0,0,2,0,160,0
53167,6,25,Es_6_3,Other,11.12.2014 14:23:30,11.12.2014 14:23:30,0,0,0,2,0,32,0
53168,6,25,Es_6_3,Other,11.12.2014 14:23:31,11.12.2014 14:23:32,0,0,0,3,0,77,0
53169,6,25,Es_6_3,Blank,11.12.2014 14:23:33,11.12.2014 14:23:34,0,0,0,1,0,79,0

Input log data:

In [8]:
logs = pd.read_csv('/Users/Mysun/Desktop/HU 530/530 - Project/EPM Dataset 2/Data/logs.txt', sep='\t')

In [9]:
logs.head()

,Student Id,Session 1,Session 2,Session 3,Session 4,Session 5,Session 6
0,1,1,1,0,1,1,1
1,2,1,1,1,1,1,1
2,3,0,1,1,1,1,0
3,4,1,1,1,1,1,1
4,5,1,1,1,1,1,1

Keep students who attend all 6 sessions

In [10]:
ID_list = pd.DataFrame(columns=['Student Id'])  
ID_list = logs.loc[(logs["Session 1"]==1) & (logs["Session 2"]==1) & (logs["Session 3"]==1) & (logs["Session 4"]==1) & (logs["Session 5"]==1) & (logs["Session 6"]==1)]

Final grades data:

In [11]:
final_grades_1st = pd.read_excel('/Users/Mysun/Desktop/HU 530/530 - Project/EPM Dataset 2/Data/final_grades.xlsx', sheet_name='Exam (First time)')
final_grades_2nd = pd.read_excel('/Users/Mysun/Desktop/HU 530/530 - Project/EPM Dataset 2/Data/final_grades.xlsx', sheet_name='Exam (Second time)')

In [12]:
final_grades_1st.head()

,Student ID,ES 1.1 (2 points),ES 1.2 (3 points),ES 2.1 (2 points),ES 2.2 (3 points),ES 3.1 (1 points),ES 3.2 (2 points),ES 3.3 (2 points),ES 3.4 (2 points),ES 3.5 (3 points),ES 4.1 (15 points),ES 4.2 (10 points),ES 5.1 (2 points),ES 5.2 (10 points),ES 5.3 (3 points),ES 6.1 (25 points),ES 6.2 (15 points),TOTAL (100 points)
0,3,2.0,3,1.0,2.0,1,2,2,2.0,3.0,15.0,10.0,1,5.0,3.0,18.0,15,85.0
1,6,2.0,3,2.0,3.0,1,2,2,0.0,3.0,15.0,7.0,2,9.0,3.0,13.0,15,82.0
2,7,2.0,3,1.0,1.5,1,2,0,0.0,3.0,5.0,4.0,0,0.0,3.0,17.0,10,52.5
3,10,2.0,3,2.0,1.5,1,2,0,2.0,3.0,11.0,1.0,2,10.0,1.5,7.0,10,59.0
4,13,2.0,3,2.0,1.5,1,2,2,2.0,3.0,14.5,10.0,2,2.0,3.0,25.0,15,90.0

In [13]:
final_grades_2nd.head()

,Student ID,ES 1.1 (2 points),ES 1.2 (3 points),ES 2.1 (2 points),ES 2.2 (3 points),ES 3.1 (1 points),ES 3.2 (2 points),ES 3.3 (2 points),ES 3.4 (2 points),ES 3.5 (3 points),ES 4.1 (15 points),ES 4.2 (10 points),ES 5.1 (2 points),ES 5.2 (10 points),ES 5.3 (3 points),ES 6.1 (25 points),ES 6.2 (15 points),TOTAL (100 points)
0,1,2.0,3.0,1.0,0.5,1.0,2,2.0,2,3,15,10.0,2.0,10.0,3.0,25.0,13.0,94.5
1,2,2.0,3.0,2.0,0.5,1.0,2,0.0,2,3,15,2.0,0.0,5.0,1.5,5.0,0.0,44.0
2,4,2.0,3.0,1.0,0.5,1.0,2,0.0,2,0,3,4.0,0.0,1.5,0.0,5.0,5.0,30.0
3,5,2.0,3.0,2.0,1.5,1.0,2,2.0,2,3,3,2.0,1.5,9.0,1.5,2.0,1.0,38.5
4,7,2.0,3.0,1.0,1.5,1.0,2,2.0,2,3,15,10.0,1.0,2.5,0.0,20.0,12.0,78.0

Combine two final scores and use average score for students who have 2 scores

In [14]:
final = final_grades_1st.append(final_grades_2nd)
final.sort_values(by=['Student ID'])

,Student ID,ES 1.1 (2 points),ES 1.2 (3 points),ES 2.1 (2 points),ES 2.2 (3 points),ES 3.1 (1 points),ES 3.2 (2 points),ES 3.3 (2 points),ES 3.4 (2 points),ES 3.5 (3 points),ES 4.1 (15 points),ES 4.2 (10 points),ES 5.1 (2 points),ES 5.2 (10 points),ES 5.3 (3 points),ES 6.1 (25 points),ES 6.2 (15 points),TOTAL (100 points)
0,1,2.0,3.0,1.0,0.5,1.0,2,2.0,2.0,3.0,15.0,10.0,2.0,10.0,3.0,25.0,13.0,94.5
1,2,2.0,3.0,2.0,0.5,1.0,2,0.0,2.0,3.0,15.0,2.0,0.0,5.0,1.5,5.0,0.0,44.0
0,3,2.0,3.0,1.0,2.0,1.0,2,2.0,2.0,3.0,15.0,10.0,1.0,5.0,3.0,18.0,15.0,85.0
2,4,2.0,3.0,1.0,0.5,1.0,2,0.0,2.0,0.0,3.0,4.0,0.0,1.5,0.0,5.0,5.0,30.0
3,5,2.0,3.0,2.0,1.5,1.0,2,2.0,2.0,3.0,3.0,2.0,1.5,9.0,1.5,2.0,1.0,38.5
1,6,2.0,3.0,2.0,3.0,1.0,2,2.0,0.0,3.0,15.0,7.0,2.0,9.0,3.0,13.0,15.0,82.0
4,7,2.0,3.0,1.0,1.5,1.0,2,2.0,2.0,3.0,15.0,10.0,1.0,2.5,0.0,20.0,12.0,78.0
2,7,2.0,3.0,1.0,1.5,1.0,2,0.0,0.0,3.0,5.0,4.0,0.0,0.0,3.0,17.0,10.0,52.5
5,8,0.5,3.0,0.0,0.0,1.0,2,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.5
6,9,2.0,3.0,1.0,0.5,1.0,2,2.0,2.0,3.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,18.5
3,10,2.0,3.0,2.0,1.5,1.0,2,0.0,2.0,3.0,11.0,1.0,2.0,10.0,1.5,7.0,10.0,59.0
7,11,2.0,3.0,1.0,0.5,1.0,2,2.0,2.0,3.0,12.0,3.0,2.0,8.0,1.5,12.0,5.0,60.0
8,12,2.0,3.0,0.5,2.0,1.0,2,0.0,2.0,3.0,15.0,2.0,0.5,5.5,2.0,0.0,0.0,40.5
4,13,2.0,3.0,2.0,1.5,1.0,2,2.0,2.0,3.0,14.5,10.0,2.0,2.0,3.0,25.0,15.0,90.0
9,14,2.0,3.0,2.0,3.0,1.0,2,2.0,2.0,3.0,3.0,10.0,2.0,8.0,3.0,9.0,9.0,64.0
5,15,2.0,3.0,1.0,2.0,1.0,2,2.0,2.0,3.0,15.0,10.0,2.0,4.0,1.5,2.0,15.0,67.5
6,16,2.0,3.0,1.0,0.0,1.0,2,2.0,2.0,3.0,3.0,9.0,1.0,0.0,3.0,20.0,15.0,67.0
7,17,2.0,3.0,1.0,2.0,1.0,2,2.0,2.0,3.0,15.0,10.0,2.0,10.0,3.0,24.0,15.0,97.0
8,18,1.0,3.0,2.0,3.0,1.0,2,2.0,2.0,3.0,15.0,7.0,2.0,2.5,1.5,5.0,10.0,62.0
10,19,2.0,3.0,1.0,2.0,1.0,2,2.0,2.0,3.0,15.0,3.0,1.5,2.0,1.5,5.0,4.0,50.0
11,20,2.0,3.0,2.0,3.0,1.0,2,2.0,2.0,3.0,15.0,10.0,2.0,8.0,3.0,25.0,14.5,97.5
9,20,2.0,3.0,2.0,0.0,1.0,2,2.0,2.0,1.5,15.0,10.0,0.0,0.0,3.0,5.0,10.0,58.5
12,22,2.0,3.0,1.0,0.5,1.0,2,2.0,0.0,3.0,4.0,0.0,0.0,0.0,1.5,10.0,10.0,40.0
10,24,2.0,3.0,1.0,1.5,1.0,2,2.0,2.0,3.0,11.0,1.0,0.0,0.0,3.0,0.0,0.0,32.5
13,24,2.0,3.0,1.0,0.5,1.0,2,2.0,2.0,3.0,15.0,4.0,2.0,10.0,3.0,15.0,5.0,70.5
14,25,2.0,3.0,2.0,0.0,1.0,2,2.0,2.0,3.0,15.0,5.0,2.0,10.0,1.5,2.0,5.0,57.5
11,27,2.0,3.0,1.0,2.0,1.0,2,0.0,2.0,3.0,15.0,9.0,0.0,0.0,0.0,24.5,10.0,74.5
12,28,2.0,3.0,1.0,2.0,1.0,2,2.0,2.0,0.0,15.0,8.5,2.0,4.0,3.0,19.0,13.0,79.5
13,29,2.0,3.0,2.0,0.0,1.0,2,2.0,2.0,3.0,15.0,10.0,2.0,10.0,3.0,25.0,15.0,97.0
14,30,0.0,0.0,2.0,0.0,0.0,0,0.0,0.0,0.0,3.0,2.0,0.0,0.0,0.0,0.0,0.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47,79,2.0,3.0,1.0,1.5,0.5,2,2.0,2.0,3.0,13.0,4.0,1.0,9.0,1.5,25.0,14.0,84.5
48,80,2.0,3.0,1.0,0.5,1.0,2,2.0,2.0,3.0,7.0,4.0,0.0,7.5,1.5,5.0,10.0,51.5
37,81,2.0,3.0,1.0,0.0,1.0,2,2.0,2.0,3.0,15.0,7.0,2.0,4.0,3.0,25.0,15.0,87.0
49,82,2.0,3.0,1.0,0.5,1.0,2,0.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,13.5
50,83,2.0,3.0,2.0,0.5,1.0,0,2.0,2.0,0.0,7.0,5.0,0.5,7.0,0.0,13.0,7.0,52.0
38,83,2.0,3.0,2.0,0.0,1.0,2,0.0,2.0,0.0,3.0,3.0,2.0,4.0,1.5,10.0,0.0,35.5
39,85,2.0,3.0,2.0,1.5,1.0,2,2.0,2.0,3.0,13.0,10.0,2.0,0.0,1.5,25.0,12.0,82.0
40,86,2.0,3.0,2.0,3.0,1.0,2,2.0,2.0,3.0,15.0,10.0,1.0,5.0,3.0,25.0,15.0,94.0
41,87,2.0,3.0,1.5,1.5,1.0,2,2.0,2.0,3.0,3.0,4.0,0.0,0.0,0.0,8.0,13.0,46.0
51,87,2.0,3.0,1.0,2.0,1.0,2,2.0,2.0,3.0,15.0,10.0,2.0,10.0,1.5,10.0,8.0,74.5
42,88,2.0,3.0,1.0,2.0,1.0,2,2.0,2.0,3.0,15.0,10.0,2.0,8.0,3.0,25.0,15.0,96.0
43,89,2.0,3.0,1.5,0.0,1.0,2,0.0,2.0,3.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,16.5
52,91,2.0,2.0,1.0,2.0,1.0,2,2.0,2.0,3.0,5.0,10.0,0.0,5.5,2.0,17.0,10.0,66.5
44,92,1.5,3.0,1.0,0.0,1.0,2,0.0,2.0,0.0,3.0,6.0,0.0,0.0,0.0,0.0,0.0,19.5
53,92,2.0,3.0,2.0,0.5,1.0,2,0.0,2.0,0.0,15.0,3.0,1.0,2.5,1.0,0.0,0.0,35.0
45,93,2.0,3.0,2.0,1.5,1.0,2,2.0,2.0,3.0,3.0,6.0,0.0,0.0,1.5,24.0,13.0,66.0
54,94,2.0,3.0,1.0,2.0,1.0,2,2.0,2.0,3.0,15.0,8.5,2.0,9.0,2.0,25.0,13.0,92.5
55,95,2.0,3.0,1.0,0.5,1.0,2,0.0,2.0,3.0,15.0,8.0,0.0,0.0,0.0,10.0,5.0,52.5
46,96,2.0,3.0,2.0,1.5,1.0,2,2.0,2.0,3.0,15.0,7.0,2.0,10.0,3.0,12.0,10.0,77.5
47,98,2.0,3.0,1.0,2.0,1.0,2,2.0,2.0,3.0,13.0,10.0,2.0,4.0,1.5,10.0,8.0,66.5
48,99,1.5,3.0,0.0,0.0,1.0,2,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.5
56,99,2.0,2.0,0.0,0.0,1.0,2,0.0,2.0,3.0,2.0,3.0,0.0,0.0,0.0,0.0,0.0,17.0
49,100,2.0,3.0,1.0,1.5,1.0,2,2.0,2.0,3.0,13.0,7.0,2.0,8.0,1.5,24.0,10.0,83.0
57,101,2.0,2.0,1.0,2.0,1.0,2,1.5,2.0,2.0,5.0,1.0,0.0,0.0,1.5,4.0,5.0,32.0
50,101,2.0,3.0,0.5,1.0,1.0,2,0.0,0.0,3.0,3.0,3.0,0.0,0.0,0.0,0.0,0.0,18.5
58,102,2.0,3.0,1.0,1.5,1.0,0,0.0,2.0,3.0,12.0,3.0,0.0,0.0,0.0,2.0,1.0,31.5
59,103,2.0,3.0,1.0,1.5,1.0,2,0.0,2.0,3.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,18.5
60,104,2.0,3.0,1.0,1.5,1.0,2,2.0,2.0,3.0,15.0,9.0,2.0,8.0,3.0,24.5,13.0,92.0
51,106,2.0,3.0,1.5,0.0,1.0,2,2.0,2.0,3.0,3.0,4.0,0.0,0.0,0.0,7.0,15.0,45.5
61,106,2.0,3.0,1.0,1.5,1.0,2,2.0,2.0,3.0,7.0,7.5,1.0,1.5,1.5,25.0,10.0,71.0

Keep students who join all 6 sessions

In [15]:
final = final[final['Student ID'].isin(ID_list['Student Id'])]

In [16]:
#find duplicated rows
d_row = final[final['Student ID'].duplicated(keep=False)]

In [17]:
#drop these duplicated rows first
final.drop(d_row.index,axis=0,inplace=True)

In [18]:
#calculate mean for duplicated rows
g_items=d_row.groupby('Student ID').mean()
g_items['Student ID']=g_items.index

In [19]:
#combine two DataFrames
final=final.append(g_items)
final.sort_values(by=['Student ID'])

/Users/Mysun/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:6692: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)

,ES 1.1 (2 points),ES 1.2 (3 points),ES 2.1 (2 points),ES 2.2 (3 points),ES 3.1 (1 points),ES 3.2 (2 points),ES 3.3 (2 points),ES 3.4 (2 points),ES 3.5 (3 points),ES 4.1 (15 points),ES 4.2 (10 points),ES 5.1 (2 points),ES 5.2 (10 points),ES 5.3 (3 points),ES 6.1 (25 points),ES 6.2 (15 points),Student ID,TOTAL (100 points)
1,2.00,3.0,2.00,0.50,1.0,2,0.0,2.0,3.00,15.00,2.0,0.0,5.00,1.50,5.00,0.00,2,44.00
3,2.00,3.0,2.00,1.50,1.0,2,2.0,2.0,3.00,3.00,2.0,1.5,9.00,1.50,2.00,1.00,5,38.50
7,2.00,3.0,1.00,1.50,1.0,2,1.0,1.0,3.00,10.00,7.0,0.5,1.25,1.50,18.50,11.00,7,65.25
3,2.00,3.0,2.00,1.50,1.0,2,0.0,2.0,3.00,11.00,1.0,2.0,10.00,1.50,7.00,10.00,10,59.00
7,2.00,3.0,1.00,0.50,1.0,2,2.0,2.0,3.00,12.00,3.0,2.0,8.00,1.50,12.00,5.00,11,60.00
8,2.00,3.0,0.50,2.00,1.0,2,0.0,2.0,3.00,15.00,2.0,0.5,5.50,2.00,0.00,0.00,12,40.50
5,2.00,3.0,1.00,2.00,1.0,2,2.0,2.0,3.00,15.00,10.0,2.0,4.00,1.50,2.00,15.00,15,67.50
7,2.00,3.0,1.00,2.00,1.0,2,2.0,2.0,3.00,15.00,10.0,2.0,10.00,3.00,24.00,15.00,17,97.00
10,2.00,3.0,1.00,2.00,1.0,2,2.0,2.0,3.00,15.00,3.0,1.5,2.00,1.50,5.00,4.00,19,50.00
20,2.00,3.0,2.00,1.50,1.0,2,2.0,2.0,2.25,15.00,10.0,1.0,4.00,3.00,15.00,12.25,20,78.00
12,2.00,3.0,1.00,2.00,1.0,2,2.0,2.0,0.00,15.00,8.5,2.0,4.00,3.00,19.00,13.00,28,79.50
30,1.00,1.5,2.00,1.00,0.5,1,1.0,1.0,1.50,7.50,5.0,0.5,2.50,0.75,2.00,2.50,30,31.25
17,2.00,3.0,2.00,0.50,1.0,2,1.5,2.0,0.00,4.00,0.0,0.0,0.00,0.00,0.00,0.00,34,18.00
16,2.00,3.0,1.00,0.00,1.0,1,0.0,2.0,3.00,13.00,9.0,2.0,10.00,3.00,16.00,13.00,36,79.00
19,2.00,3.0,2.00,0.50,1.0,2,2.0,2.0,3.00,15.00,4.0,1.0,2.50,1.50,0.00,0.00,38,41.50
39,2.00,3.0,1.50,0.00,0.5,0,0.0,2.0,0.00,9.00,7.0,1.0,4.00,1.25,17.00,14.00,39,62.25
21,2.00,3.0,1.00,0.50,1.0,2,0.0,2.0,3.00,4.00,2.0,0.5,0.00,1.50,0.00,0.00,42,22.50
44,2.00,3.0,1.50,2.50,1.0,2,2.0,2.0,3.00,9.00,8.5,1.0,7.50,3.00,14.00,11.75,44,73.75
51,1.50,1.5,0.25,0.00,1.0,2,1.0,1.0,0.00,0.00,0.5,0.0,0.00,0.00,0.00,0.00,51,8.75
28,2.00,2.0,2.00,0.00,1.0,2,0.0,0.0,0.00,4.00,2.0,0.0,0.00,3.00,8.00,10.00,52,36.00
24,1.00,3.0,1.00,1.00,1.0,2,2.0,2.0,3.00,15.00,7.0,1.0,8.00,1.50,12.00,10.00,53,70.50
29,2.00,3.0,1.00,1.50,1.0,2,0.0,2.0,3.00,15.00,2.0,0.0,5.00,1.50,0.00,0.00,54,39.00
56,2.00,3.0,2.00,2.50,1.0,2,2.0,1.0,1.50,15.00,10.0,1.5,7.00,2.25,16.50,8.50,56,77.75
59,1.00,3.0,2.00,0.00,0.5,2,1.0,2.0,1.50,3.00,5.0,1.5,5.25,1.50,2.50,3.00,59,34.75
29,2.00,3.0,2.00,3.00,1.0,2,2.0,2.0,3.00,15.00,10.0,2.0,8.00,3.00,18.00,10.00,66,86.00
67,2.00,3.0,0.75,1.00,1.0,2,2.0,2.0,3.00,14.75,10.0,2.0,7.50,3.00,19.75,12.50,67,86.25
42,2.00,3.0,2.00,2.00,1.0,2,2.0,2.0,3.00,15.00,8.5,1.0,0.00,0.00,12.00,5.00,70,60.50
35,2.00,3.0,2.00,1.50,1.0,2,2.0,2.0,2.00,15.00,10.0,2.0,10.00,3.00,24.00,12.00,76,93.50
36,2.00,3.0,1.00,2.00,1.0,2,2.0,2.0,3.00,15.00,4.0,0.0,5.00,1.50,24.50,10.00,78,78.00
47,2.00,3.0,1.00,1.50,0.5,2,2.0,2.0,3.00,13.00,4.0,1.0,9.00,1.50,25.00,14.00,79,84.50
48,2.00,3.0,1.00,0.50,1.0,2,2.0,2.0,3.00,7.00,4.0,0.0,7.50,1.50,5.00,10.00,80,51.50
37,2.00,3.0,1.00,0.00,1.0,2,2.0,2.0,3.00,15.00,7.0,2.0,4.00,3.00,25.00,15.00,81,87.00
49,2.00,3.0,1.00,0.50,1.0,2,0.0,0.0,0.00,2.00,2.0,0.0,0.00,0.00,0.00,0.00,82,13.50
40,2.00,3.0,2.00,3.00,1.0,2,2.0,2.0,3.00,15.00,10.0,1.0,5.00,3.00,25.00,15.00,86,94.00
87,2.00,3.0,1.25,1.75,1.0,2,2.0,2.0,3.00,9.00,7.0,1.0,5.00,0.75,9.00,10.50,87,60.25
42,2.00,3.0,1.00,2.00,1.0,2,2.0,2.0,3.00,15.00,10.0,2.0,8.00,3.00,25.00,15.00,88,96.00
52,2.00,2.0,1.00,2.00,1.0,2,2.0,2.0,3.00,5.00,10.0,0.0,5.50,2.00,17.00,10.00,91,66.50
92,1.75,3.0,1.50,0.25,1.0,2,0.0,2.0,0.00,9.00,4.5,0.5,1.25,0.50,0.00,0.00,92,27.25
45,2.00,3.0,2.00,1.50,1.0,2,2.0,2.0,3.00,3.00,6.0,0.0,0.00,1.50,24.00,13.00,93,66.00
54,2.00,3.0,1.00,2.00,1.0,2,2.0,2.0,3.00,15.00,8.5,2.0,9.00,2.00,25.00,13.00,94,92.50
47,2.00,3.0,1.00,2.00,1.0,2,2.0,2.0,3.00,13.00,10.0,2.0,4.00,1.50,10.00,8.00,98,66.50

Create pass(final score >=60)/ fail(final score <60) column

In [20]:
final.head()

,ES 1.1 (2 points),ES 1.2 (3 points),ES 2.1 (2 points),ES 2.2 (3 points),ES 3.1 (1 points),ES 3.2 (2 points),ES 3.3 (2 points),ES 3.4 (2 points),ES 3.5 (3 points),ES 4.1 (15 points),ES 4.2 (10 points),ES 5.1 (2 points),ES 5.2 (10 points),ES 5.3 (3 points),ES 6.1 (25 points),ES 6.2 (15 points),Student ID,TOTAL (100 points)
3,2.0,3.0,2.0,1.5,1.0,2,0.0,2.0,3.0,11.0,1.0,2.0,10.0,1.5,7.0,10.0,10,59.0
5,2.0,3.0,1.0,2.0,1.0,2,2.0,2.0,3.0,15.0,10.0,2.0,4.0,1.5,2.0,15.0,15,67.5
7,2.0,3.0,1.0,2.0,1.0,2,2.0,2.0,3.0,15.0,10.0,2.0,10.0,3.0,24.0,15.0,17,97.0
12,2.0,3.0,1.0,2.0,1.0,2,2.0,2.0,0.0,15.0,8.5,2.0,4.0,3.0,19.0,13.0,28,79.5
16,2.0,3.0,1.0,0.0,1.0,1,0.0,2.0,3.0,13.0,9.0,2.0,10.0,3.0,16.0,13.0,36,79.0

In [21]:
final['Pass_IND'] = [1 if x >=60 else 0 for x in final['TOTAL\n(100 points)']]

In [22]:
final.head()

,ES 1.1 (2 points),ES 1.2 (3 points),ES 2.1 (2 points),ES 2.2 (3 points),ES 3.1 (1 points),ES 3.2 (2 points),ES 3.3 (2 points),ES 3.4 (2 points),ES 3.5 (3 points),ES 4.1 (15 points),ES 4.2 (10 points),ES 5.1 (2 points),ES 5.2 (10 points),ES 5.3 (3 points),ES 6.1 (25 points),ES 6.2 (15 points),Student ID,TOTAL (100 points),Pass_IND
3,2.0,3.0,2.0,1.5,1.0,2,0.0,2.0,3.0,11.0,1.0,2.0,10.0,1.5,7.0,10.0,10,59.0,0
5,2.0,3.0,1.0,2.0,1.0,2,2.0,2.0,3.0,15.0,10.0,2.0,4.0,1.5,2.0,15.0,15,67.5,1
7,2.0,3.0,1.0,2.0,1.0,2,2.0,2.0,3.0,15.0,10.0,2.0,10.0,3.0,24.0,15.0,17,97.0,1
12,2.0,3.0,1.0,2.0,1.0,2,2.0,2.0,0.0,15.0,8.5,2.0,4.0,3.0,19.0,13.0,28,79.5,1
16,2.0,3.0,1.0,0.0,1.0,1,0.0,2.0,3.0,13.0,9.0,2.0,10.0,3.0,16.0,13.0,36,79.0,1

Intermediate grades data:

In [23]:
inter_grades = pd.read_excel('/Users/Mysun/Desktop/HU 530/530 - Project/EPM Dataset 2/Data/intermediate_grades.xlsx')

In [38]:
inter_grades.head()

   Student Id  Session 2  Session 3  Session 4  Session 5  Session 6
0           1        5.0        0.0        4.5        4.0       2.25
1           2        4.0        3.5        4.5        4.0       1.00
2           3        3.5        3.5        4.5        4.0       0.00
3           4        6.0        4.0        5.0        3.5       2.75
4           5        5.0        4.0        5.0        4.0       2.75

Standardization data with zero mean and unit variance

In [40]:
from sklearn import preprocessing
inter_grades['Session 1 scaled'] = preprocessing.scale(inter_grades['Session 1'])

KeyError: 'Session 1'

# Accessing Data

There are some 0 scores in the intermediate grades dataset, and we know that the logs dataset marked all the student has log in a session with value 1, while those has not log in a session with value 0, so here comes the question: were all the students without log got a 0 score in the intermediate grades?

We can use the test below to check this question:

In [25]:
no_inter_grades = (inter_grades == 0)
no_inter_grades

     Student Id  Session 2  Session 3  Session 4  Session 5  Session 6
0         False      False       True      False      False      False
1         False      False      False      False      False      False
2         False      False      False      False      False       True
3         False      False      False      False      False      False
4         False      False      False      False      False      False
5         False      False      False      False      False      False
6         False      False      False      False      False      False
7         False      False      False      False      False       True
8         False       True      False      False      False      False
9         False      False      False      False      False      False
10        False      False      False      False      False      False
11        False      False      False      False      False      False
12        False       True       True      False      False      False
13        False      False      False      False      False      False
14        False      False      False      False      False      False
15        False      False      False      False      False      False
16        False      False      False      False      False      False
17        False      False      False      False      False      False
18        False      False      False      False      False      False
19        False      False      False      False      False      False
20        False      False       True      False       True       True
21        False      False       True      False      False       True
22        False       True      False      False      False       True
23        False      False      False      False      False      False
24        False       True      False      False      False      False
25        False       True       True      False       True       True
26        False       True      False      False      False      False
27        False      False      False      False      False      False
28        False      False      False      False      False      False
29        False      False      False      False      False      False
..          ...        ...        ...        ...        ...        ...
85        False      False      False      False      False      False
86        False      False      False      False      False      False
87        False      False      False      False      False      False
88        False      False      False      False      False      False
89        False      False      False      False      False      False
90        False      False      False      False      False      False
91        False      False      False      False      False      False
92        False      False      False      False      False      False
93        False      False      False      False      False      False
94        False      False      False      False      False      False
95        False      False       True      False      False      False
96        False      False      False      False       True      False
97        False      False      False      False      False      False
98        False      False      False      False      False      False
99        False      False      False       True      False      False
100       False      False      False       True      False       True
101       False      False      False      False      False      False
102       False      False       True       True      False       True
103       False      False       True      False      False      False
104       False       True      False       True       True       True
105       False       True      False       True       True       True
106       False       True      False       True       True       True
107       False       True       True       True       True       True
108       False       True       True       True       True       True
109       False       True       True       True       True       True
110       False      False       True       True      False       True
111       False       True       True       True       True       True
112       False       True       True       True       True       True
113       False       True       True       True       True       True
114       False       True       True       True       True       True

[115 rows x 6 columns]

In [26]:
no_log = (logs == 0)
no_log

,Student Id,Session 1,Session 2,Session 3,Session 4,Session 5,Session 6
0,False,False,False,True,False,False,False
1,False,False,False,False,False,False,False
2,False,True,False,False,False,False,True
3,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False
5,False,True,False,False,False,False,False
6,False,False,False,False,False,False,False
7,False,True,False,False,False,False,True
8,False,False,True,False,False,False,False
9,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False
12,False,True,True,True,False,False,False
13,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False
15,False,True,False,False,False,False,False
16,False,False,False,False,False,False,False
17,False,True,False,False,False,False,False
18,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False
20,False,False,False,True,False,True,True
21,False,False,False,True,False,False,True
22,False,True,True,False,False,False,True
23,False,True,False,False,False,False,False
24,False,True,True,False,False,True,False
25,False,True,True,True,False,True,True
26,False,True,False,False,False,False,False
27,False,False,False,False,False,False,False
28,False,True,False,False,False,False,False
29,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...
85,False,False,False,False,False,False,False
86,False,False,False,False,False,False,False
87,False,False,False,False,False,False,False
88,False,True,True,False,False,False,False
89,False,False,False,False,False,False,False
90,False,False,False,False,False,False,False
91,False,False,False,False,False,False,False
92,False,False,False,False,False,False,False
93,False,False,False,False,False,False,False
94,False,True,False,False,False,False,False
95,False,False,False,True,False,False,False
96,False,False,False,False,False,True,False
97,False,False,False,False,False,False,False
98,False,True,False,False,False,False,False
99,False,False,False,False,True,False,True
100,False,False,False,False,True,False,True
101,False,False,False,False,True,False,False
102,False,True,False,True,True,False,True
103,False,False,False,True,True,False,False
104,False,False,True,False,True,True,True
105,False,True,True,False,True,True,True
106,False,True,False,False,True,True,True
107,False,False,True,True,True,True,True
108,False,False,True,True,True,True,True
109,False,False,True,True,True,True,True
110,False,False,True,True,True,True,True
111,False,False,True,True,True,True,True
112,False,False,True,True,True,True,True
113,False,False,True,True,True,True,True
114,False,False,True,True,True,True,True

In [27]:
no_log.drop('Session 1', axis=1, inplace=True)

In [28]:
no_log

     Student Id  Session 2  Session 3  Session 4  Session 5  Session 6
0         False      False       True      False      False      False
1         False      False      False      False      False      False
2         False      False      False      False      False       True
3         False      False      False      False      False      False
4         False      False      False      False      False      False
5         False      False      False      False      False      False
6         False      False      False      False      False      False
7         False      False      False      False      False       True
8         False       True      False      False      False      False
9         False      False      False      False      False      False
10        False      False      False      False      False      False
11        False      False      False      False      False      False
12        False       True       True      False      False      False
13        False      False      False      False      False      False
14        False      False      False      False      False      False
15        False      False      False      False      False      False
16        False      False      False      False      False      False
17        False      False      False      False      False      False
18        False      False      False      False      False      False
19        False      False      False      False      False      False
20        False      False       True      False       True       True
21        False      False       True      False      False       True
22        False       True      False      False      False       True
23        False      False      False      False      False      False
24        False       True      False      False       True      False
25        False       True       True      False       True       True
26        False      False      False      False      False      False
27        False      False      False      False      False      False
28        False      False      False      False      False      False
29        False      False      False      False      False      False
..          ...        ...        ...        ...        ...        ...
85        False      False      False      False      False      False
86        False      False      False      False      False      False
87        False      False      False      False      False      False
88        False       True      False      False      False      False
89        False      False      False      False      False      False
90        False      False      False      False      False      False
91        False      False      False      False      False      False
92        False      False      False      False      False      False
93        False      False      False      False      False      False
94        False      False      False      False      False      False
95        False      False       True      False      False      False
96        False      False      False      False       True      False
97        False      False      False      False      False      False
98        False      False      False      False      False      False
99        False      False      False       True      False       True
100       False      False      False       True      False       True
101       False      False      False       True      False      False
102       False      False       True       True      False       True
103       False      False       True       True      False      False
104       False       True      False       True       True       True
105       False       True      False       True       True       True
106       False      False      False       True       True       True
107       False       True       True       True       True       True
108       False       True       True       True       True       True
109       False       True       True       True       True       True
110       False       True       True       True       True       True
111       False       True       True       True       True       True
112       False       True       True       True       True       True
113       False       True       True       True       True       True
114       False       True       True       True       True       True

[115 rows x 6 columns]

In [29]:
no_grade_contrast = (no_log != no_inter_grades)

In [30]:
no_grade_contrast.loc[no_grade_contrast['Session 2'] == True]

     Student Id  Session 2  Session 3  Session 4  Session 5  Session 6
26        False       True      False      False      False      False
34        False       True      False      False      False      False
54        False       True      False      False      False       True
59        False       True       True      False      False      False
60        False       True      False      False      False      False
65        False       True      False      False      False      False
67        False       True      False      False      False      False
88        False       True      False      False      False      False
106       False       True      False      False      False      False
110       False       True      False      False       True      False

All those True values means that not all the no log students get a zero score in intermediate grades. We can dig into those student Id to have a look of it.

In [31]:
se2_index = no_grade_contrast.loc[no_grade_contrast['Session 2'] == True].index

In [32]:
inter_grades.iloc[se2_index]

     Student Id  Session 2  Session 3  Session 4  Session 5  Session 6
26           27        0.0        3.0        4.5        4.0       1.75
34           35        0.5        0.5        3.5        3.5       1.50
54           55        2.0        3.5        4.5        4.0       2.50
59           60        2.0        0.5        4.0        3.5       1.00
60           61        0.0        1.0        4.5        3.5       1.50
65           66        0.0        2.0        4.5        3.0       2.25
67           68        5.5        3.5        5.0        4.0       3.00
88           89        0.5        1.5        3.5        2.5       0.50
106         107        0.0        1.0        0.0        0.0       0.00
110         111        3.0        0.0        0.0        3.0       0.00

In [33]:
logs.iloc[se2_index]

,Student Id,Session 1,Session 2,Session 3,Session 4,Session 5,Session 6
26,27,0,1,1,1,1,1
34,35,0,0,1,1,1,1
54,55,1,0,1,1,1,0
59,60,0,0,0,1,1,1
60,61,0,1,1,1,1,1
65,66,1,1,1,1,1,1
67,68,1,0,1,1,1,1
88,89,0,0,1,1,1,1
106,107,0,1,1,0,0,0
110,111,1,0,0,0,0,0

It is quite strange that student id 27 has log in session 2 but get a 0 score, while student id 35 has no log in session 2 but get a 0.5 score. Based on the dataset description, students has no log means he or she did not access that session and cannot get a grade for that session. This is a data quality problem.

* So we decide use the intermediate grades regardless of the logs.

The final grades has 2 datasets: first exam and second exam, some student attend both exams, and the detail of both exams are different but addressed the same concepts. We can check who attended both exams:

In [34]:
attend_1st_id = np.asarray(final_grades_1st['Student ID'])
attend_2nd_id = np.asarray(final_grades_2nd['Student ID'])

In [35]:
def common_member(a, b):
    a_set = set(a)
    b_set = set(b)
    if (a_set & b_set):
        print(a_set & b_set)
    else:
        print('No common elements')

In [36]:
common_member(attend_1st_id, attend_2nd_id)

{7, 20, 24, 30, 37, 39, 44, 46, 51, 56, 59, 62, 67, 68, 73, 83, 87, 92, 99, 101, 106}

# Cleaning Data

In [37]:
#only take higher grade for final score

# Exploratory Data Analysis

# Classification

## Building Model

## Model Evaluation

# Clustering

# Process Mining

# Conclusions